import type { CSSProperties } from "react";
import { GRID } from "./constants";

/** Co-located styles for the PR list page (extracted from inline styles). */
export const s = {
  row: (hover: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: GRID,
    alignItems: "center",
    gap: 14,
    padding: "12px 20px",
    borderBottom: "1px solid var(--border)",
    cursor: "pointer",
    background: hover ? "var(--bg-surface)" : "transparent",
    transition: "background .1s",
  }),
  rowTitleCell: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  rowIcon: (color: string): CSSProperties => ({ color, flexShrink: 0 }),
  rowTitleWrap: { minWidth: 0 } satisfies CSSProperties,
  rowTitle: (hover: boolean): CSSProperties => ({
    fontSize: 14,
    fontWeight: 550,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    color: hover ? "var(--accent-text)" : "var(--text-primary)",
  }),
  rowNumber: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  authorCell: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sizeBadgeBorder: (color: string): CSSProperties => ({ border: `1px solid ${color}` }),
  scoreCell: { display: "flex", alignItems: "center" } satisfies CSSProperties,
  costCell: {
    display: "flex",
    alignItems: "center",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  updatedCell: {
    fontSize: 12,
    color: "var(--text-muted)",
    textAlign: "right",
  } satisfies CSSProperties,
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
  // FINDINGS cell — severity counts that reveal a read-only preview on hover.
  findingsCell: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    width: "fit-content",
    cursor: "help",
  } satisfies CSSProperties,
  findingsCount: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    fontWeight: 600,
    color,
    borderBottom: `1px dotted ${color}`,
    paddingBottom: 1,
  }),
  findingsPopup: (placement: "up" | "down"): CSSProperties => ({
    position: "absolute",
    left: 0,
    ...(placement === "up" ? { bottom: "100%", marginBottom: 8 } : { top: "100%", marginTop: 8 }),
    zIndex: 30,
    width: 360,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 10,
    boxShadow: "var(--shadow-modal)",
    padding: 12,
    animation: "ddpop .12s ease",
    cursor: "default",
    textAlign: "left",
  }),
  findingsPopupTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    marginBottom: 9,
  } satisfies CSSProperties,
  findingsPopupList: {
    display: "flex",
    flexDirection: "column",
    gap: 9,
    maxHeight: 300,
    overflow: "auto",
  } satisfies CSSProperties,
  findingsPopupItem: (last: boolean): CSSProperties => ({
    paddingBottom: last ? 0 : 9,
    borderBottom: last ? "none" : "1px solid var(--border)",
  }),
  findingsPopupHead: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  findingsPopupMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "5px 0 0",
  } satisfies CSSProperties,
  findingsPopupLocation: { fontSize: 11, color: "var(--accent-text)" } satisfies CSSProperties,
  findingsPopupRationale: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
    marginTop: 5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } as CSSProperties,
  findingsPopupEmpty: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  filterBar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 20px",
    borderBottom: "1px solid var(--border)",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  filterChips: { display: "flex", gap: 8 } satisfies CSSProperties,
  filterActions: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  pageHeader: {
    padding: "24px 32px 10px",
    display: "flex",
    alignItems: "flex-end",
    gap: 16,
  } satisfies CSSProperties,
  pageTitle: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  pageSubtitle: {
    fontSize: 14,
    color: "var(--text-secondary)",
    marginTop: 4,
  } satisfies CSSProperties,
  headerActions: {
    marginLeft: "auto",
    display: "flex",
    gap: 10,
    alignItems: "center",
  } satisfies CSSProperties,
  tableCard: {
    margin: "14px 32px 44px",
    border: "1px solid var(--border)",
    borderRadius: 10,
    // visible, not hidden: the FINDINGS hover popup is absolutely positioned
    // inside a row and would be clipped at the card's edge otherwise.
    overflow: "visible",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  headRow: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 14,
    padding: "10px 20px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  headCell: (alignRight: boolean): CSSProperties => ({
    textAlign: alignRight ? "right" : "left",
  }),
  loadingStack: {
    padding: 20,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
} as const;
