import type { CSSProperties } from "react";

/** Co-located styles for the skill editor's Stats tab. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  hint: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginBottom: 16,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  statRow: { display: "flex", gap: 12, marginBottom: 20 } satisfies CSSProperties,
  stat: {
    flex: 1,
    padding: 15,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  statHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
  } satisfies CSSProperties,
  statValue: {
    marginTop: 10,
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  statSuffix: { fontSize: 15, color: "var(--text-muted)" } satisfies CSSProperties,
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
    alignItems: "start",
  } satisfies CSSProperties,
  agentList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  agentRow: (enabled: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    opacity: enabled ? 1 : 0.6,
  }),
  agentIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  agentName: {
    fontSize: 12.5,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  donutWrap: { display: "grid", placeItems: "center", paddingTop: 6 } satisfies CSSProperties,
  sevRow: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  empty: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  footnote: {
    marginTop: 18,
    fontSize: 11.5,
    color: "var(--text-muted)",
    lineHeight: 1.6,
  } satisfies CSSProperties,
} as const;
